import { GuidelineStep, PackageItem, Volunteer } from './types.ts';

export const APP_LINKS = {
  RECIPIENT_REGISTRATION: "https://ee.kobo.asf.sh/x/E2KzbCY0",
  VOLUNTEER_SHEET: "https://docs.google.com/spreadsheets/d/1VzXRlAXdhEUpgokQB6P72SIIqGYh8_ScnwEkzU7OF8o/edit?gid=0#gid=0",
  YOUTUBE_TUTORIAL: "https://youtu.be/mA8hFEQNIik",
  FACEBOOK_1: "https://www.facebook.com/sakibulislamrc1",
  FACEBOOK_2: "https://www.facebook.com/Bismahsoftbd",
  YOUTUBE: "https://www.youtube.com/@sakibulislamrc",
  INSTAGRAM: "https://www.instagram.com/sakibulislamrc"
};

export const PROJECT_INSTRUCTIONS = {
  title: "ইফতার বিতরণ প্রকল্প ২০২৬: স্থানীয় স্বেচ্ছাসেবকদের প্রতি নির্দেশনা",
  intro: "এবছর দেশের প্রত্যন্ত নদীভাঙনপ্রবণ অঞ্চল, হাওর অঞ্চল, উপকূলীয় অঞ্চল, চরাঞ্চল, পার্বত্য এলাকা, বন্যাপ্রবণ নিচু এলাকা, চা-বাগান এলাকা, প্রত্যন্ত গ্রামীণ এলাকার ৩৩,৩০০ অসহায়, দরিদ্র, এতিম, বিধবা, বৃদ্ধ ও প্রতিবন্ধী সিয়াম পালনকারী ব্যক্তিদের মধ্যে ইফতার প্যাকেজ বিতরণ করা হবে। উক্ত প্রকল্প বাস্তবায়নের সকল পর্যায়ে আপনারা সততা, নিষ্ঠা ও নিরপেক্ষতার সঙ্গে কাজ করবেন ইনশাআল্লাহ।",
  steps: [
    {
      title: "কমিটি গঠন ও পরিকল্পনা",
      text: "পুরো কার্যক্রম সুন্দরভাবে সম্পন্ন করার জন্য আপনার এলাকার গ্রহণযোগ্য ও নির্ভরযোগ্য ব্যক্তিদের নিয়ে ৫ সদস্যের একটি কমিটি গঠন করবেন। কমিটির প্রত্যেক সদস্যকে ১০/২০ জন উপকারভোগীর দায়িত্ব প্রদান করবেন। অফিসিয়াল দায়িত্বশীলের নির্দেশনা অনুযায়ী সর্বমোট ৫০/১০০ জন উপকারভোগীর তালিকা করতে হবে। কমিটির সদস্যদের নাম, মোবাইল নম্বর এবং পেশা অফিসিয়াল দায়িত্বশীলকে দিবেন।"
    },
    {
      title: "উপকারভোগী নির্বাচন",
      text: "সম্পূর্ণ মানবিক, নিরপেক্ষ ও অরাজনৈতিক ভিত্তিতে উপকারভোগী নির্বাচন করবেন। তালিকা করার ক্ষেত্রে অনিয়মিত দিনমজুর, ভিক্ষাবৃত্তি বা অন্যের সহায়তার উপর নির্ভরশীল পরিবার, অতি দরিদ্র পরিবার, বিধবা, বৃদ্ধ, প্রতিবন্ধী, এতিম, গৃহহীনদের প্রাধান্য দিবেন।"
    },
    {
      title: "তথ্য প্রদান (Kobo Toolbox)",
      text: "প্রদানকৃত Kobo Toolbox এর লিংকে প্রবেশ করে প্রস্তাবিত উপকারভোগীদের পূর্ণাঙ্গ তথ্য প্রদান করবেন। তথ্য প্রদান করলেই তা চূড়ান্ত বলে গণ্য হবে না; আপনাদের প্রেরিত উপকারভোগীদের তথ্য যাচাই ও পর্যালোচনা করে চূড়ান্ত অনুমোদন প্রদান করবে সংশ্লিষ্ট কর্তৃপক্ষ।"
    },
    {
      title: "বিতরণ প্রস্তুতি ও কার্যক্রম",
      text: "ইফতার প্যাকেজ কুরিয়ারে হোম ডেলিভারিতে পাঠানো হবে। বিতরণের আগ পর্যন্ত প্যাকেজগুলো নিরাপদ স্থানে সংরক্ষণ করবেন। জনসমাগম ও বিশৃঙ্খলা এড়ানোর জন্য সবাইকে এক স্থানে একত্রিত না করে, প্রত্যেক উপকারভোগীর বাড়িতে গিয়ে ইফতার প্যাকেজ পৌঁছে দিবেন।"
    },
    {
      title: "দাওয়াহ ও ডকুমেন্টেশন",
      text: "প্রত্যেকটি বাড়িতে দাওয়াহ প্রদান করবেন (ঈমান, ইসলাম, সালাত, সিয়াম ইত্যাদি)। যার হাতে ইফতার প্যাকেজ তুলে দিবেন সেই ব্যক্তিকে তার ঘরের সামনে দাঁড় করিয়ে একটি ছবি তুলবেন এবং Kobo Toolbox এর মাধ্যমে আমাদের কাছে পাঠিয়ে দিবেন। কেউ ছবি তুলতে অস্বাচ্ছন্দ্যবোধ করলে বাচ্চাদের দিয়ে বা শুধু প্যাকেজের ছবি তুলবেন।"
    },
    {
      title: "হিসাব ও ভাউচার প্রদান",
      text: "পেপার প্রিন্ট, পরিবহন, যাতায়াত ও অন্যান্য সকল খরচয়ের হিসাব ভাউচারসহ অফিসিয়াল দায়িত্বশীকে লিখিতভাবে বুঝিয়ে দিবেন। পরবর্তীতে এই খরচগুলো বিকাশ, নগদ বা অন্য যে কোনো মাধ্যমে পরিশোধ করা হবে। ভাউচার ছাড়া বিল পরিশোধ করা সম্ভব হবে না।"
    }
  ],
  closing: "কোনো অনিয়ম বা জটিলতা দেখা দিলে তাৎক্ষণিকভাবে অফিসিয়াল দায়িত্বশীকে অবহিত করবেন। রাজনৈতিক বা ব্যক্তিগত প্রভাবমুক্ত থেকে স্বচ্ছতার সঙ্গে পুরো কার্যক্রম সম্পন্ন করবেন, ইনশাআল্লাহ।"
};

export const IFTAR_PACKAGE: PackageItem[] = [
  { name: "খেজুর", quantity: "১ কেজি", icon: "fa-seedling" },
  { name: "ছোলা", quantity: "২ কেজি", icon: "fa-bowl-rice" },
  { name: "মশুর ডাল", quantity: "২ কেজি", icon: "fa-wheat-awn" },
  { name: "মুড়ি", quantity: "১ কেজি", icon: "fa-cloud" },
  { name: "সয়াবিন তেল", quantity: "১ লিটার", icon: "fa-bottle-droplet" }
];

export const GUIDELINES: GuidelineStep[] = [
  {
    title: "কমিটি গঠন",
    description: "এলাকার নির্ভরযোগ্য ব্যক্তিদের নিয়ে ৫ সদস্যের কমিটি গঠন করুন।",
    icon: "fa-users",
    details: ["৫ সদস্যের কমিটি", "৫১-১০০ উপকারভোগীর তালিকা"]
  },
  {
    title: "উপকারভোগী নির্বাচন",
    description: "মানবিক ও নিরপেক্ষ ভিত্তিতে দরিদ্রদের নির্বাচন করুন।",
    icon: "fa-user-check",
    details: ["অরাজনৈতিক দৃষ্টিভঙ্গি", "অসহায়দের অগ্রাধিকার"]
  },
  {
    title: "তথ্য সাবমিশন",
    description: "Kobo Toolbox লিংকে তথ্য প্রদান করুন।",
    icon: "fa-clipboard-list",
    details: ["নির্ভুল তথ্য প্রদান", "যাচাইয়ের পর অনুমোদন"]
  }
];

export const VOLUNTEERS: Volunteer[] = [
  { spotCode: "101", name: "মোঃ সজিব মিয়া", mobile: "1722632650", district: "রংপুর", upazila: "গংগাচড়া" },
  { spotCode: "102", name: "জুহার আলমাস লাবিব", mobile: "1402298830", district: "রংপুর", upazila: "পীরগাছা" },
  { spotCode: "103", name: "মো: জিসান ইসলাম জিহাদ", mobile: "1518969970", district: "রংপুর", upazila: "পীরগঞ্জ" },
  { spotCode: "104", name: "মোঃ আরিফুল ইসলাম", mobile: "1834192907", district: "রংপুর", upazila: "মিঠাপুকুর" },
  { spotCode: "105", name: "আল মুতাকাব্বির", mobile: "1709331789", district: "রংপুর", upazila: "রংপুর সদর" },
  { spotCode: "106", name: "Md. Jobayer Ahmed", mobile: "1890500353", district: "রংপুর", upazila: "বদরগঞ্জ" },
  { spotCode: "107", name: "মো: হাবিবুল বাসার সুমন", mobile: "1758396258", district: "রংপুর", upazila: "তারাগঞ্জ" },
  { spotCode: "108", name: "মোঃ রোমান বাবু", mobile: "1318095091", district: "রংপুর", upazila: "Mitha Pukur" },
  { spotCode: "109", name: "মোঃ ঈসা রুহুল্লাহ", mobile: "1723111292", district: "রংপুর", upazila: "Taraganj" },
  { spotCode: "110", name: "মেহেরাব হোসাইন লিখন", mobile: "1328728998", district: "রংপুর", upazila: "Pirganj R" },
  { spotCode: "111", name: "রেহাত", mobile: "1301152102", district: "রংপুর", upazila: "সদর" },
  { spotCode: "112", name: "মোঃ আজাদ হোসাইন", mobile: "1738292835", district: "কুড়িগ্রাম", upazila: "চর রাজিবপুর" },
  { spotCode: "113", name: "মো: আরমান মিয়া", mobile: "1302187133", district: "কুড়িগ্রাম", upazila: "রাজারহাট" },
  { spotCode: "114", name: "মোঃ আসাদুজ্জামান আলিফ", mobile: "1917971368", district: "কুড়িগ্রাম", upazila: "Raumari" },
  { spotCode: "115", name: "মো আল আমিন", mobile: "1935568526", district: "কুড়িগ্রাম", upazila: "Raumari" },
  { spotCode: "116", name: "ফজলে রাব্বি", mobile: "1786971958", district: "কুড়িগ্রাম", upazila: "রাজারহাট" },
  { spotCode: "117", name: "মোঃ ইমাম হাসান", mobile: "1907496844", district: "কুড়িগ্রাম", upazila: "চর রাজিবপুর" },
  { spotCode: "118", name: "মাওলানা সোহেল", mobile: "1736020732", district: "কুড়িগ্রাম", upazila: "উলিপুর" },
  { spotCode: "119", name: "Md Mijanur Rahman Biju", mobile: "1915164514", district: "কুড়িগ্রাম", upazila: "চিলমারী" },
  { spotCode: "120", name: "মুহা. আলমগীর হুসাইন", mobile: "1963228687", district: "কুড়িগ্রাম", upazila: "রৌমারী" },
  { spotCode: "121", name: "মো: মাহমুদুল হাসান", mobile: "1869644712", district: "কুড়িগ্রাম", upazila: "রৌমারী" },
  { spotCode: "122", name: "জহুরুল", mobile: "1745522808", district: "কুড়িগ্রাম", upazila: "কুড়িগ্রাম সদর" },
  { spotCode: "123", name: "মাওলানা মুফতি সাইফুল ইসলাম", mobile: "1760454669", district: "কুড়িগ্রাম", upazila: "ফুলবাড়ি" },
  { spotCode: "124", name: "মোঃ ফারুক হোসেন", mobile: "1793903386", district: "কুড়িগ্রাম", upazila: "ফুলবাড়ী" },
  { spotCode: "125", name: "মো: রাসেল খন্দকার", mobile: "1571224186", district: "কুড়িগ্রাম", upazila: "ফুলবাড়ি" },
  { spotCode: "126", name: "মাওলানা রেজাউল", mobile: "1916941954", district: "কুড়িগ্রাম", upazila: "নাগেশ্বরী" },
  { spotCode: "127", name: "জাহিদুল ইসলাম জাহিদ", mobile: "1714882910", district: "কুড়িগ্রাম", upazila: "ভুরুঙ্গামারী" },
  { spotCode: "128", name: "মোঃ সাদিকুল ইসলাম", mobile: "1798969486", district: "লালমনিরহাট", upazila: "আদিতমারী" },
  { spotCode: "129", name: "মোস্তফা জামান", mobile: "1904191104", district: "লালমনিরহাট", upazila: "পাটগ্রাম" },
  { spotCode: "130", name: "Rashed Munna", mobile: "1905937921", district: "লালমনিরহাট", upazila: "পাটগ্রাম" },
  { spotCode: "131", name: "ইবনে আল সিফাত", mobile: "1310112229", district: "লালমনিরহাট", upazila: "পাটগ্রাম" },
  { spotCode: "132", name: "রতন সরকার", mobile: "1730968876", district: "লালমনিরহাট", upazila: "লালমনিরহাট সদর" },
  { spotCode: "133", name: "মো. ফজলুল হক", mobile: "1619859004", district: "লালমনিরহাট", upazila: "লালমনিরহাট সদর" },
  { spotCode: "134", name: "মুফতি আব্দুল হান্নান সাইফি", mobile: "1737988273", district: "লালমনিরহাট", upazila: "হাতিবান্ধা" },
  { spotCode: "135", name: "মোঃ নাজমুল হক", mobile: "1796977157", district: "লালমনিরহাট", upazila: "হাতিবান্ধা" },
  { spotCode: "136", name: "মো: হৃদয় মিয়া", mobile: "1775043897", district: "লালমনিরহাট", upazila: "হাতিবান্ধা" },
  { spotCode: "137", name: "মা. মাহফুজ", mobile: "1712800962", district: "নীলফামারী", upazila: "সৈয়দপুর" },
  { spotCode: "138", name: "মাহমুদ বিন আলম", mobile: "1794972711", district: "নীলফামারী", upazila: "ডোমার" },
  { spotCode: "139", name: "মোঃ হাসান আলী", mobile: "1761074851", district: "লালমনিরহাট", upazila: "আদিতমারী" },
  { spotCode: "140", name: "Md. Abu Sayed", mobile: "1930808104", district: "নীলফামারী", upazila: "Domar" },
  { spotCode: "141", name: "Rohmatullah Makki", mobile: "1571421846", district: "নীলফামারী", upazila: "Saidpur" },
  { spotCode: "142", name: "মো শাহিন ইসলাম", mobile: "1572773962", district: "নীলফামারী", upazila: "নীলফামারী সদর" },
  { spotCode: "143", name: "জিহান", mobile: "1753742510", district: "নীলফামারী", upazila: "ডিমলা" },
  { spotCode: "144", name: "মোঃ আব্দুস সালাম", mobile: "1767191303", district: "নীলফামারী", upazila: "নীলফামারী সদর" },
  { spotCode: "145", name: "SHSHADAT", mobile: "1757724933", district: "নীলফামারী", upazila: "কিশোরগঞ্জ" },
  { spotCode: "146", name: "মোঃ রেজাকুল ইসলাম রিপন", mobile: "1314184460", district: "ঠাকুরগাঁও", upazila: "বালিয়াডাঙ্গী" },
  { spotCode: "147", name: "Md Mithun Rana", mobile: "1753766256", district: "ঠাকুরগাঁও", upazila: "Pirganj" },
  { spotCode: "148", name: "মো রায়হান আলী", mobile: "1794820404", district: "ঠাকুরগাঁও", upazila: "Baliadangi" },
  { spotCode: "149", name: "MD TOWKIR HASAN", mobile: "1781966325", district: "ঠাকুরগাঁও", upazila: "Baliadangi" },
  { spotCode: "150", name: "মোবাসির হোসেন", mobile: "1863432304", district: "ঠাকুরগাঁও", upazila: "Sadar" },
  { spotCode: "151", name: "মোঃ নাইমুল আলী", mobile: "1763072933", district: "ঠাকুরগাঁও", upazila: "Ranisankail" },
  { spotCode: "152", name: "হাফেজ আবু হানিফ", mobile: "1751461219", district: "ঠাকুরগাঁও", upazila: "ঠাকুরগাঁও সদর" },
  { spotCode: "153", name: "আবু সালেহ", mobile: "1738022918", district: "ঠাকুরগাঁও", upazila: "পীরগঞ্জ" },
  { spotCode: "154", name: "শফিকুল ইসলাম", mobile: "1314275512", district: "ঠাকুরগাঁও", upazila: "হরিপুর" },
  { spotCode: "155", name: "MD MAHMUD HASAN", mobile: "1724217602", district: "পঞ্চগড়", upazila: "দেবীগঞ্জ" },
  { spotCode: "156", name: "মোঃহাবিবুল্লাহ বাবুল", mobile: "1706765118", district: "পঞ্চগড়", upazila: "দেবীগঞ্জ" },
  { spotCode: "157", name: "মুফতি আব্দুল্লাহ আল হুসাইন", mobile: "1717413274", district: "পঞ্চগড়", upazila: "তেঁতুলিয়া" },
  { spotCode: "158", name: "সাদমান প্রধান", mobile: "1810355882", district: "পঞ্চগড়", upazila: "পঞ্চগড় সদর" },
  { spotCode: "159", name: "Md Maruf Rahman", mobile: "1305681490", district: "পঞ্চগড়", upazila: "Debiganj" },
  { spotCode: "160", name: "Md. Farhad Hossion.", mobile: "1795787525", district: "পঞ্চগড়", upazila: "BODA" },
  { spotCode: "161", name: "Md Jahedul Islam", mobile: "1789270625", district: "পঞ্চগড়", upazila: "BODA" },
  { spotCode: "162", name: "আরিফ হোসেন", mobile: "1707310085", district: "পঞ্চগড়", upazila: "পঞ্চগড় সদর" },
  { spotCode: "163", name: "মুফতি আহমাদুল্লাহ মাসরুর", mobile: "1722276260", district: "পঞ্চগড়", upazila: "পঞ্চগড় সদর" },
  { spotCode: "164", name: "খাদিমুল ইসলাম", mobile: "1763070564", district: "পঞ্চগড়", upazila: "পঞ্চগড় সদর" },
  { spotCode: "165", name: "হাফেজ শিহাব মাহমুদ", mobile: "1773504275", district: "পঞ্চগড়", upazila: "আটোয়ারী" },
  { spotCode: "166", name: "শামীম আশরাফ", mobile: "1324105764", district: "দিনাজপুর", upazila: "দিনাজপুর সদর" },
  { spotCode: "167", name: "মাওলানা আবু হুরায়রা", mobile: "1768852978", district: "দিনাজপুর", upazila: "বিরামপুর" },
  { spotCode: "168", name: "হাফেজ ফিরুজ", mobile: "1797635164", district: "দিনাজপুর", upazila: "বিরল" },
  { spotCode: "169", name: "মুফতি আনোয়ার", mobile: "1723791003", district: "দিনাজপুর", upazila: "বোচাগঞ্জ" },
  { spotCode: "170", name: "সেলিম শাহ", mobile: "1300367429", district: "দিনাজপুর", upazila: "চিরিরবন্দর" },
  { spotCode: "171", name: "শাহীদ খান", mobile: "1714017326", district: "দিনাজপুর", upazila: "ফুলবাড়ী" },
  { spotCode: "172", name: "MD Biplob Hosen", mobile: "1749158282", district: "দিনাজপুর", upazila: "Bochaganj" },
  { spotCode: "173", name: "রিয়াজ ইসলাম", mobile: "1707386421", district: "দিনাজপুর", upazila: "বীরগঞ্জ" },
  { spotCode: "174", name: "মো: বিপ্লব হোসেন", mobile: "1717039788", district: "দিনাজপুর", upazila: "Birganj" },
  { spotCode: "175", name: "MD. Shahid Islam", mobile: "1316244257", district: "দিনাজপুর", upazila: "Birganj" },
  { spotCode: "176", name: "শাহীন রেজা", mobile: "1762830444", district: "দিনাজপুর", upazila: "ঘোড়াঘাট" },
  { spotCode: "177", name: "মুফতি নূরুল করিম সাহেব", mobile: "1717763009", district: "দিনাজপুর", upazila: "হাকিমপুর" },
  { spotCode: "178", name: "ডাক্তার সাজু", mobile: "1720583656", district: "দিনাজপুর", upazila: "খানসামা" },
  { spotCode: "179", name: "মাহবুব", mobile: "1732098542", district: "দিনাজপুর", upazila: "নবাবগঞ্জ" },
  { spotCode: "180", name: "মুফতি হোসাইন আহমাদ।", mobile: "1740533631", district: "দিনাজপুর", upazila: "পার্বতীপুর" },
  { spotCode: "181", name: "মো: আশরাফুল ইসলাম", mobile: "1774416161", district: "গাইবান্ধা", upazila: "গাইবান্ধা সদর" },
  { spotCode: "182", name: "মো আল আমিন হোসেন আরিফ", mobile: "1989195326", district: "গাইবান্ধা", upazila: "Sadullapur" },
  { spotCode: "183", name: "Md Refat Mia", mobile: "1305646584", district: "গাইবান্ধা", upazila: "Sundarganj" },
  { spotCode: "184", name: "Md. Rayhan Sorker", mobile: "1750434618", district: "গাইবান্ধা", upazila: "Gaibandha Sadar" },
  { spotCode: "185", name: "আবির হোসেন", mobile: "1518984848", district: "গাইবান্ধা", upazila: "Sundarganj" },
  { spotCode: "186", name: "মোঃ আব্দুল লতিফ সরকার", mobile: "1818115991", district: "গাইবান্ধা", upazila: "Gobindaganj" },
  { spotCode: "187", name: "MD. ROBIUL HASAN", mobile: "1877544343", district: "গাইবান্ধা", upazila: "Gobindaganj" },
  { spotCode: "188", name: "MD. SAKIB HASAN SIYAM", mobile: "1572918797", district: "গাইবান্ধা", upazila: "Gobindaganj" },
  { spotCode: "189", name: "মোঃ রুবেল মিয়া", mobile: "1764989119", district: "গাইবান্ধা", upazila: "Sundarganj" },
  { spotCode: "190", name: "মোঃ জুবায়ের আল মাহমুদ (ওহি)", mobile: "1754090532", district: "গাইবান্ধা", upazila: "সাঘাটা" },
  { spotCode: "191", name: "আহসান হাবীব তুহিন", mobile: "1327817200", district: "গাইবান্ধা", upazila: "Sadullapur" },
  { spotCode: "192", name: "মোঃ আজিজুল হক", mobile: "1875026999", district: "গাইবান্ধা", upazila: "Sundarganj" },
  { spotCode: "193", name: "মশিউর রহমান", mobile: "1975314713", district: "গাইবান্ধা", upazila: "সাঘাটা" },
  { spotCode: "194", name: "শামসুল ইসলাম", mobile: "1750281050", district: "গাইবান্ধা", upazila: "পলাশবাড়ী" },
  { spotCode: "195", name: "হাফেজ মোহাম্মাদ রাশেদুল ইসলাম", mobile: "1307924378", district: "গাইবান্ধা", upazila: "পলাশবাড়ী" },
  { spotCode: "196", name: "রাশেদুল ইসলাম", mobile: "1714881946", district: "গাইবান্ধা", upazila: "গোবিন্দগঞ্জ" },
  { spotCode: "197", name: "আবু সাঈদ মুহা মোজাহীদ", mobile: "1722277808", district: "গাইবান্ধা", upazila: "সুন্দরগঞ্জ" },
  { spotCode: "198", name: "মোতাহার হোসেন", mobile: "1750636428", district: "রাজশাহী", upazila: "রাজশাহী সদর" },
  { spotCode: "199", name: "লামিম হাসান শ্রাবণ", mobile: "1834443894", district: "রাজশাহী", upazila: "চারঘাট" },
  { spotCode: "200", name: "মোঃ আমিনুল ইসলাম", mobile: "1761646912", district: "রাজশাহী", upazila: "বাঘা" },
  { spotCode: "201", name: "KHADEM MAHMUD", mobile: "1718844688", district: "রাজশাহী", upazila: "পুঠিয়া" },
  { spotCode: "202", name: "মোঃ ইস্রাফিল হোসেন", mobile: "1721462454", district: "রাজশাহী", upazila: "তানোর" },
  { spotCode: "203", name: "Md Habibullah", mobile: "1776836608", district: "রাজশাহী", upazila: "মোহনপুর" },
  { spotCode: "204", name: "মোঃ সাকিবুল ইসলাম সাব্বির।", mobile: "1345417317", district: "রাজশাহী", upazila: "দুর্গাপুর" },
  { spotCode: "205", name: "শাইখ হাফেজ মাসুদুর রহমান", mobile: "1757844439", district: "রাজশাহী", upazila: "বাগমারা" },
  { spotCode: "206", name: "শরিফুল ইসলাম", mobile: "1744161475", district: "রাজশাহী", upazila: "গোদাগাড়ী" },
  { spotCode: "207", name: "সিয়াম", mobile: "1757658714", district: "নাটোর", upazila: "নাটোর সদর" },
  { spotCode: "208", name: "md mridul ahmed", mobile: "1580763421", district: "নাটোর", upazila: "gurudaspur" },
  { spotCode: "209", name: "ওমর ফারুক", mobile: "1797992330", district: "নাটোর", upazila: "বাগাতিপাড়া" },
  { spotCode: "210", name: "Md. Zahid Sarkar", mobile: "1301355349", district: "নাটোর", upazila: "বরাইগ্রাম" },
  { spotCode: "211", name: "শায়খ শহীদুল ইসলাম", mobile: "1719035915", district: "নাটোর", upazila: "গুরুদাসপুর" },
  { spotCode: "212", name: "মোঃ নয়ন ইসলাম", mobile: "1819207829", district: "নাটোর", upazila: "বরাইগ্রাম" },
  { spotCode: "213", name: "Md Ariful Islam", mobile: "1403784841", district: "নাটোর", upazila: "গুরুদাসপুর" },
  { spotCode: "214", name: "মো: ইমন আলী", mobile: "1786151052", district: "নাটোর", upazila: "সিংড়া" },
  { spotCode: "215", name: "M.M RATUL", mobile: "1772728561", district: "নওগাঁ", upazila: "নওগাঁ সদর" },
  { spotCode: "216", name: "মাও. মিজান হোসাইন", mobile: "1739409262", district: "নওগাঁ", upazila: "নওগাঁ সদর" },
  { spotCode: "217", name: "MD.FOYSAL", mobile: "1319854215", district: "নওগাঁ", upazila: "নিয়ামতপুর" },
  { spotCode: "218", name: "আল মুকিত", mobile: "1721809750", district: "নওগাঁ", upazila: "ধামুরহাট" },
  { spotCode: "219", name: "Mohammod ALi", mobile: "1560013884", district: "চাঁপাইনবাবগঞ্জ", upazila: "চাঁপাইনবাবগঞ্জ সদর" },
  { spotCode: "220", name: "Shakil Ahmed Sifat", mobile: "1794346110", district: "চাঁপাইনবাবগঞ্জ", upazila: "গোমস্তাপুর" },
  { spotCode: "221", name: "Ali Hasan", mobile: "1572902439", district: "চাঁপাইনবাবগঞ্জ", upazila: "Gomastapur" },
  { spotCode: "222", name: "Md. Siddiqur Rahman Sayed", mobile: "1314583604", district: "চাঁপাইনবাবগঞ্জ", upazila: "চাপাইনবাবগঞ্জ সদর" },
  { spotCode: "223", name: "রাফিউল ইসলাম", mobile: "1304676238", district: "চাঁপাইনবাবগঞ্জ", upazila: "শিবগঞ্জ" },
  { spotCode: "224", name: "মো. সামিউল হোসেন", mobile: "1732917671", district: "পাবনা", upazila: "পাবনা সদর" },
  { spotCode: "225", name: "Md Hasibur Rahman Shanto", mobile: "1795979890", district: "পাবনা", upazila: "Sujanagar" },
  { spotCode: "226", name: "খন্দকার শোয়াইব রহমান", mobile: "1315923079", district: "পাবনা", upazila: "পাবনা সদর" },
  { spotCode: "227", name: "মাওলানা আব্দুল হান্নান", mobile: "1323308334", district: "পাবনা", upazila: "সুজানগর" },
  { spotCode: "228", name: "আব্দুল হাই", mobile: "1939363834", district: "পাবনা", upazila: "ঈশ্বরদী" },
  { spotCode: "229", name: "রাশেদ মামুন", mobile: "1681700441", district: "সিরাজগঞ্জ", upazila: "উল্লাপাড়া" },
  { spotCode: "230", name: "মোঃ সুজন রানা", mobile: "1701993361", district: "সিরাজগঞ্জ", upazila: "কাজীপুর" },
  { spotCode: "231", name: "Muhammad Al-habib", mobile: "1766976266", district: "সিরাজগঞ্জ", upazila: "Sirajganj Sadar" },
  { spotCode: "232", name: "মোঃ আব্দুল খালেক", mobile: "1827841614", district: "সিরাজগঞ্জ", upazila: "Ullah Para" },
  { spotCode: "233", name: "মো:মুরছালিন মোল্লা", mobile: "01516510202", district: "সিরাজগঞ্জ", upazila: "বেলকুচি" },
  { spotCode: "234", name: "মো: আবু সামা", mobile: "1647264308", district: "সিরাজগঞ্জ", upazila: "চৌহালী" },
  { spotCode: "235", name: "Md. Abu Raihan", mobile: "1319884011", district: "সিরাজগঞ্জ", upazila: "রায়গঞ্জ" },
  { spotCode: "236", name: "আ. রহিম", mobile: "1789493628", district: "সিরাজগঞ্জ", upazila: "শলঙ্গা থানা" },
  { spotCode: "237", name: "মোঃ শরীয়াতুল ইসলাম সজল", mobile: "1328273845", district: "সিরাজগঞ্জ", upazila: "Shahjadpur_Shar" },
  { spotCode: "238", name: "মোঃ সাজ্জাদুল ইসলাম", mobile: "1788243731", district: "সিরাজগঞ্জ", upazila: "Sirajganj Sadar" },
  { spotCode: "239", name: "মোঃ ইয়াসিন আরাফাত", mobile: "1819672837", district: "সিরাজগঞ্জ", upazila: "Sirajganj Sadar" },
  { spotCode: "240", name: "এসএম রবিউল ইসলাম", mobile: "1767723991", district: "সিরাজগঞ্জ", upazila: "Ullah Para" },
  { spotCode: "241", name: "MD.SOJIB HOSSAIN", mobile: "1777272587", district: "সিরাজগঞ্জ", upazila: "বেলকুচি" },
  { spotCode: "242", name: "মোঃ মাহবুব আলম", mobile: "1853383848", district: "সিরাজগঞ্জ", upazila: "শাহজাদপুর" },
  { spotCode: "243", name: "আলহাজ্ব মাওলানা কে এম সুলতান মাহমুদ", mobile: "1761617912", district: "বগুড়া", upazila: "ধুনট" },
  { spotCode: "244", name: "Md.Badol Miah", mobile: "1784025395", district: "বগুড়া", upazila: "সারিয়াকান্দি" },
  { spotCode: "245", name: "MD.Moshiur Hasan", mobile: "1740530392", district: "বগুড়া", upazila: "সারিয়াকান্দি" },
  { spotCode: "246", name: "আব্দুল কাইয়ুম", mobile: "1776634302", district: "বগুড়া", upazila: "গাবতলী" },
  { spotCode: "247", name: "Md Mahmudur Rahman", mobile: "1879119823", district: "বগুড়া", upazila: "আদমদিঘী" },
  { spotCode: "248", name: "মিল্লাত", mobile: "1785592790", district: "বগুড়া", upazila: "সোনাতলা" },
  { spotCode: "249", name: "মোঃ ইয়ামিম", mobile: "1608453001", district: "বগুড়া", upazila: "ধুনট" },
  { spotCode: "250", name: "Md Naim Shaikh", mobile: "1308607738", district: "বগুড়া", upazila: "ধুনট" },
  { spotCode: "251", name: "মো: মিনহাজ উদ্দিন", mobile: "1890967570", district: "বগুড়া", upazila: "শিবগঞ্জ" },
  { spotCode: "252", name: "নিয়ামতউল্লাহ", mobile: "1719520492", district: "বগুড়া", upazila: "আদমদিঘী" },
  { spotCode: "253", name: "মাওলানা আসআদুল্লাহ সাহেব", mobile: "1712213160", district: "জয়পুরহাট", upazila: "জয়পুরহাট সদর" },
  { spotCode: "254", name: "Naimur Rahman", mobile: "1522108246", district: "জয়পুরহাট", upazila: "আক্কেলপুর" },
  { spotCode: "255", name: "মো শাহিনুর আলম", mobile: "1774039777", district: "জয়পুরহাট", upazila: "কালাই" },
  { spotCode: "256", name: "মোঃ রিফাত হাসান", mobile: "1722445851", district: "জয়পুরহাট", upazila: "পাঁচবিবি" },
  { spotCode: "257", name: "Mohammad Nazmus Sakib", mobile: "1852828418", district: "জয়পুরহাট", upazila: "জয়পুরহাট সদর" },
  { spotCode: "258", name: "মো: রাফিজুল ইসলাম", mobile: "1746728595", district: "বগুড়া", upazila: "শেরপুর" }
];